import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:easyconnect/services/client_service.dart';
import 'package:easyconnect/services/devis_service.dart';
import 'package:easyconnect/services/bordereau_service.dart';
import 'package:easyconnect/services/bon_commande_service.dart';
import 'package:easyconnect/services/bon_de_commande_fournisseur_service.dart';
import 'package:easyconnect/services/invoice_service.dart';
import 'package:easyconnect/services/payment_service.dart';
import 'package:easyconnect/services/expense_service.dart';
import 'package:easyconnect/services/salary_service.dart';
import 'package:easyconnect/services/reporting_service.dart';
import 'package:easyconnect/services/attendance_punch_service.dart';
import 'package:easyconnect/services/intervention_service.dart';
import 'package:easyconnect/services/task_service.dart';
import 'package:easyconnect/services/tax_service.dart';
import 'package:easyconnect/services/recruitment_service.dart';
import 'package:easyconnect/services/supplier_service.dart';
import 'package:easyconnect/services/stock_service.dart';
import 'package:easyconnect/services/employee_service.dart';
import 'package:easyconnect/services/contract_service.dart';
import 'package:easyconnect/services/leave_service.dart';
import 'package:easyconnect/services/equipment_service.dart';
import 'package:easyconnect/services/favorites_service.dart';
import 'package:easyconnect/services/notification_service.dart';
import 'package:easyconnect/services/comptable_dashboard_service.dart';
import 'package:easyconnect/services/commercial_dashboard_service.dart';
import 'package:easyconnect/services/technicien_dashboard_service.dart';
import 'package:easyconnect/services/rh_dashboard_service.dart';
import 'package:easyconnect/services/patron_dashboard_service.dart';

/// Providers pour les services (remplacement de Get.put/Get.find).
/// Un seul instance par service dans tout l'app.
final clientServiceProvider = Provider<ClientService>((ref) => ClientService());
final devisServiceProvider = Provider<DevisService>((ref) => DevisService());
final bordereauServiceProvider = Provider<BordereauService>((ref) => BordereauService());
final bonCommandeServiceProvider = Provider<BonCommandeService>((ref) => BonCommandeService());
final bonDeCommandeFournisseurServiceProvider = Provider<BonDeCommandeFournisseurService>((ref) => BonDeCommandeFournisseurService());
final invoiceServiceProvider = Provider<InvoiceService>((ref) => InvoiceService());
final paymentServiceProvider = Provider<PaymentService>((ref) => PaymentService());
final expenseServiceProvider = Provider<ExpenseService>((ref) => ExpenseService());
final salaryServiceProvider = Provider<SalaryService>((ref) => SalaryService());
final reportingServiceProvider = Provider<ReportingService>((ref) => ReportingService());
final attendancePunchServiceProvider = Provider<AttendancePunchService>((ref) => AttendancePunchService());
final interventionServiceProvider = Provider<InterventionService>((ref) => InterventionService());
final taskServiceProvider = Provider<TaskService>((ref) => TaskService());
final taxServiceProvider = Provider<TaxService>((ref) => TaxService());
final recruitmentServiceProvider = Provider<RecruitmentService>((ref) => RecruitmentService());
final supplierServiceProvider = Provider<SupplierService>((ref) => SupplierService());
final stockServiceProvider = Provider<StockService>((ref) => StockService());
final employeeServiceProvider = Provider<EmployeeService>((ref) => EmployeeService());
final contractServiceProvider = Provider<ContractService>((ref) => ContractService());
final leaveServiceProvider = Provider<LeaveService>((ref) => LeaveService());
final equipmentServiceProvider = Provider<EquipmentService>((ref) => EquipmentService());
final favoritesServiceProvider = Provider<FavoritesService>((ref) => FavoritesService());
final notificationServiceProvider = Provider<NotificationService>((ref) => NotificationService());
final comptableDashboardServiceProvider = Provider<ComptableDashboardService>((ref) => ComptableDashboardService());
final commercialDashboardServiceProvider = Provider<CommercialDashboardService>((ref) => CommercialDashboardService());
final technicienDashboardServiceProvider = Provider<TechnicienDashboardService>((ref) => TechnicienDashboardService());
final rhDashboardServiceProvider = Provider<RhDashboardService>((ref) => RhDashboardService());
final patronDashboardServiceProvider = Provider<PatronDashboardService>((ref) => PatronDashboardService());
